'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { 
  CheckCircle2, 
  AlertTriangle, 
  ShieldCheck, 
  Stethoscope, 
  Sprout, 
  AlertCircle 
} from 'lucide-react';
import { DetectionResult } from '@/lib/api/diseaseDetection';

interface AnalysisResultProps {
  result: DetectionResult;
}

export default function AnalysisResult({ result }: AnalysisResultProps) {
  const getSeverityColor = (sev: string) => {
    switch (sev) {
      case 'High': return 'text-danger bg-danger/10 border-danger/20';
      case 'Emergency': return 'text-danger bg-danger/10 border-danger/30 animate-pulse';
      case 'Medium': return 'text-warning bg-warning/10 border-warning/20';
      case 'Low': return 'text-primary bg-primary/10 border-primary/20';
      default: return 'text-info bg-info/10 border-info/20';
    }
  };

  const handleDownload = () => {
    const reportContent = `
=========================================
      CROPCARE AI DIAGNOSIS REPORT
=========================================
Generated on: ${new Date().toLocaleString()}

DIAGNOSIS: ${result.diseaseName}
CONFIDENCE: ${result.confidence}%
SEVERITY: ${result.severity} Risk

DESCRIPTION:
${result.description || 'No description provided.'}

SYMPTOMS:
${result.symptoms.map(s => `- ${s}`).join('\n')}

RECOMMENDED TREATMENT:
${result.treatment.map(t => `- ${t}`).join('\n')}

PREVENTION STRATEGY:
${result.prevention.map(p => `- ${p}`).join('\n')}

-----------------------------------------
Disclaimer: This report is generated by AI. 
Please consult a local agricultural expert 
before applying chemical treatments.
=========================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CropCare_Report_${result.diseaseName.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-6"
    >
      <div className="card border-primary/20 bg-primary/5 p-8">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-primary/20 flex items-center justify-center">
              <ShieldCheck className="text-primary" size={28} />
            </div>
            <div>
              <h3 className="text-2xl font-bold">Analysis Complete</h3>
              <p className="text-text-muted text-sm">Processed by CropCare AI Engine</p>
            </div>
          </div>
          <div className="text-right">
            <span className="text-[10px] font-bold uppercase tracking-widest text-text-dim block mb-1">Confidence</span>
            <span className="text-3xl font-bold text-primary">{result.confidence}%</span>
          </div>
        </div>

        <div className="p-6 rounded-2xl bg-black/20 border border-white/5 mb-6">
          <label className="text-[10px] font-bold uppercase tracking-widest text-text-dim block mb-2">Diagnosis</label>
          <div className="flex items-center justify-between mb-4">
            <p className="text-3xl font-bold">{result.diseaseName}</p>
            <span className={`badge px-4 py-1.5 rounded-xl border ${getSeverityColor(result.severity)}`}>
              {result.severity} Risk
            </span>
          </div>
          {result.description && (
            <p className="text-sm text-text-muted italic border-t border-white/5 pt-4">
              "{result.description}"
            </p>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h4 className="font-bold flex items-center gap-2 text-warning">
              <AlertCircle size={18} /> Symptoms
            </h4>
            <ul className="space-y-2">
              {result.symptoms.map((s, i) => (
                <li key={i} className="text-sm text-text-main flex items-start gap-2">
                  <div className="w-1.5 h-1.5 bg-warning rounded-full mt-1.5" /> {s}
                </li>
              ))}
            </ul>
          </div>
          <div className="space-y-4">
            <h4 className="font-bold flex items-center gap-2 text-primary">
              <Stethoscope size={18} /> Recommended Treatment
            </h4>
            <ul className="space-y-2">
              {result.treatment.map((t, i) => (
                <li key={i} className="text-sm text-text-main flex items-start gap-2">
                  <div className="w-1.5 h-1.5 bg-primary rounded-full mt-1.5" /> {t}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="card border-accent/20 bg-accent/5 p-8"
      >
        <h4 className="text-xl font-bold mb-4 flex items-center gap-2 text-accent">
          <Sprout size={24} /> Prevention Strategy
        </h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {result.prevention.map((p, i) => (
            <div key={i} className="p-4 rounded-xl bg-black/20 border border-accent/10 text-sm">
              {p}
            </div>
          ))}
        </div>
        <div className="mt-8 flex gap-3">
          <button 
            onClick={handleDownload}
            className="btn btn-primary bg-accent text-black hover:bg-yellow-500 flex-1"
          >
            Download Report
          </button>
          <button className="btn btn-ghost border-accent/20 text-accent flex-1">
            Expert Consult
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}
